builders:
  :index_issues:
    required_inputs: [".page_meta"]
    import: "tool/index_issues.dart"
    builder_factories: ["IndexIssues.new"]
    runs_before: ["built_site"]
    build_extensions: {"$package$": ["lib/all.json"]}

targets:
  $default:
    sources:
      include:
        - "lib/**"
        - "pages/**"
        - "templates/**"
        - "web/**"
        - "tool/**"
        - "$package$"
        - "pubspec.yaml"
        - "theme.yaml"
        - "website.yaml"
      exclude:
        - "pages/**/_*"
        - "pages/atom.html"
    builders:
      :index_issues:
        enabled: true
      built_site:
        options:
          emit_content_file: true

  atom_feed:
    dependencies: ["$default"]
    sources:
      include:
        - pages/atom.*

additional_public_assets:
  # This tells build_runner that these files are part of the default build
  - "pages/**"
