name: thisweekindart
description: thisweekindart.dev
repository: https://github.com/parlough/thisweekindart
homepage: https://thisweekindart.dev/
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  build: ^2.3.1
  build_runner: ^2.3.2
  build_web_compilers: ^3.2.7
  built_site:
    git:
      url: https://github.com/simolus3/built_site.git
      path: built_site
  collection: ^1.17.0
  glob: ^2.1.1
  lints: ^2.0.1
