name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
      - name: Get dependencies
        run: dart pub get
      - name: Run initial build
        run: dart run build_runner build --release
      - name: Copy into output directory
        run: dart run build_runner build --release --output web:_site
      - uses: FirebaseExtended/action-hosting-deploy@v0
        if: ${{ github.event_name == 'push' &&
          github.ref == 'refs/heads/main' &&
          github.repository == 'parlough/thisweekindart' }}
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_THISWEEKINDART }}'
          projectId: thisweekindart
          channelId: live